server:
  port: "8080"
  mode: "debug" # debug, release

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "uptime_w33d"
  sslmode: "disable"

log:
  level: "debug" # debug, info, warn, error
  encoding: "console" # json, console
